# safe: true
port: 4242
baseurl: /
url: http://localhost:4242

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      true
lsi:         false
highlighter:    false
markdown:    kramdown
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable: false

coderay:
  coderay_wrap: div
  coderay_line_numbers: inline
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: style

name: zeroed's [Jekyll] Blog
description: zeroed on Jekyll.
author: zeroed
author_email: edd.rossi@gmail.com
category_dir: categories
